-------------------------------------------------
-------------------------------------------------
-- Vehicle Safety/Insurance Hackathon Demo DDL --
-------------------------------------------------
-------------------------------------------------

SET hivevar:demo_db=nhtsa;
SET hivevar:input_folder=/data/nhtsa/raw;
SET hivevar:datalake_path=s3a://goes-se-sandbox01 ;

DROP TABLE IF EXISTS ${hivevar:demo_db}.flat_tsbs;
DROP TABLE IF EXISTS ${hivevar:demo_db}.flat_cmpl;
DROP TABLE IF EXISTS ${hivevar:demo_db}.flat_rcl;
DROP TABLE IF EXISTS ${hivevar:demo_db}.flat_inv;
DROP DATABASE IF EXISTS ${hivevar:demo_db};
CREATE DATABASE IF NOT EXISTS ${hivevar:demo_db};

-- Contains raw manufacturer communications data sourced from: 
-- https://static.nhtsa.gov/odi/ffdd/tsbs/FLAT_TSBS.zip
CREATE EXTERNAL TABLE IF NOT EXISTS ${hivevar:demo_db}.flat_tsbs (
    BULNO STRING COMMENT 'SERVICE BULLETIN NUMBER',
    BULREP STRING COMMENT 'REPLACEMENT SERVICE BULLETIN NUMBER',
    ID INT COMMENT 'NHTSA ITEM NUMBER',
    BULDTE STRING COMMENT 'DATE OF BULLETIN',
    COMPNAME STRING COMMENT 'CODE FOR FAILING COMPONENT',
    MAKETXT STRING COMMENT 'VEHICLE/EQUIPMENT MAKE',
    MODELTXT STRING COMMENT 'VEHICLE/EQUIPMENT MODEL',
    YEARTXT STRING COMMENT 'MODEL YEAR, 9999 IF UNKNOWN or N/A',
    DATEA STRING COMMENT 'DATE ADDED TO FILE',
    SUMMARY STRING COMMENT 'DESCRIPTION OF SUMMARY'
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hivevar:datalake_path}${hivevar:input_folder}/tsbs'
tblproperties ("skip.header.line.count"="0");

-- Contains raw customer complaint data sourced from: 
-- https://static.nhtsa.gov/odi/ffdd/cmpl/FLAT_CMPL.zip
CREATE EXTERNAL TABLE IF NOT EXISTS ${hivevar:demo_db}.flat_cmpl (
    CMPLID STRING COMMENT 'NHTSA INTERNAL UNIQUE SEQUENCE NUMBER',
    ODINO INT COMMENT 'NHTSA INTERNAL REFERENCE NUMBER',
    MFR_NAME STRING COMMENT 'MANUFACTURER NAME',
    MAKETXT STRING COMMENT 'VEHICLE/EQUIPMENT MAKE',
    MODELTXT STRING COMMENT 'VEHICLE/EQUIPMENT MODEL',
    YEARTXT STRING COMMENT 'MODEL YEAR, 9999 IF UNKNOWN or N/A',
    CRASH STRING COMMENT 'WAS VEHICLE INVOLVED IN A CRASH, "Y" OR "N"',
    FAILDATE STRING COMMENT 'DATE OF INCIDENT (YYYYMMDD)',
    FIRE STRING COMMENT 'WAS VEHICLE INVOLVED IN A FIRE "Y" OR "N"',
    INJURED INT COMMENT 'DESCRIPTION OF SUMMARY',
    DEATHS INT COMMENT 'NUMBER OF FATALITIES',
    COMPDESC INT COMMENT 'SPECIFIC COMPONENT  DESCRIPTION',
    CITY STRING COMMENT 'CONSUMER CITY',
    STATE STRING COMMENT 'CONSUMER STATE CODE',
    VIN STRING COMMENT 'VEHICLE VIN#',
    DATEA STRING COMMENT 'DATE ADDED TO FILE (YYYYMMDD)',
    LDATE STRING COMMENT 'DATE COMPLAINT RECEIVED BY NHTSA (YYYYMMDD)',
    MILES INT COMMENT 'VEHICLE MILEAGE AT FAILURE',
    OCCURENCES INT COMMENT 'NUMBER OF OCCURRENCES',
    CDESCR STRING COMMENT 'DESCRIPTION OF THE COMPLAINT',
    CMPL_TYPE STRING COMMENT 'SOURCE OF COMPLAINT CODE: CAG, CON, DP, EVOQ, EWR, INS, IVOQ, LETR, MAVQ, MIVQ, MVOQ, RC, RP, SVOQ, VOQ',
    POLICE_RPT_YN STRING COMMENT 'WAS INCIDENT REPORTED TO POLICE "Y" OR "N"',
    PURCH_DT STRING COMMENT 'DATE PURCHASED (YYYYMMDD)',
    ORIG_OWNER_YN STRING COMMENT 'WAS ORIGINAL OWNER "Y" OR "N"',
    ANTI_BRAKES_YN STRING COMMENT 'ANTI-LOCK BRAKES "Y" OR "N"',
    CRUISE_CONT_YN STRING COMMENT 'CRUISE CONTROL "Y" OR "N"',
    NUM_CYLS INT COMMENT 'NUMBER OF CYLINDERS',
    DRIVE_TRAIN STRING COMMENT 'DRIVE TRAIN TYPE [AWD,4WD,FWD,RWD]',
    FUEL_SYS STRING COMMENT 'FUEL SYSTEM CODE: FI = FUEL INJECTION, TB = TURBO',
    FUEL_TYPE STRING COMMENT 'FUEL TYPE CODE: BF = BIFUEL, CN = CNG/LPG, DS = DIESEL, GS = GAS, HE = HYBRID ELECTRIC',
    TRANS_TYPE STRING COMMENT 'VEHICLE TRANSMISSION TYPE [AUTO, MAN]',
    VEH_SPEED INT COMMENT 'VEHICLE SPEED',
    DOT STRING COMMENT 'DEPARTMENT OF TRANSPORTATION TIRE IDENTIFIER',
    TIRE_SIZE STRING COMMENT 'TIRE SIZE"',
    LOC_OF_TIRE STRING COMMENT 'LOCATION OF TIRE CODE: FSW, DSR, FTR, PSR, SPR',
    TIRE_FAIL_TYPE STRING COMMENT 'TYPE OF TIRE FAILURE CODE: BST=BLISTER,BLW=BLOWOUT,TTL=CRACK,OFR=OUT OF ROUND,TSW=PUNCTURE,TTR=ROAD HAZARD,TSP=TREAD SEPARATION',
    ORIG_EQUIP_YN STRING COMMENT 'WAS PART ORIGINAL EQUIPMENT "Y" OR "N"',
    MANUF_DT STRING COMMENT 'DATE OF MANUFACTURE (YYYYMMDD)',
    SEAT_TYPE STRING COMMENT 'TYPE OF CHILD SEAT CODE: B=BOOSTER,C=CONVERTIBLE,I=INFANT,IN=INTEGRATED,TD=TODDLER',
    RESTRAINT_TYPE STRING COMMENT 'INSTALLATION SYSTEM CODE: A = VEHICLE SAFETY BELT, B = LATCH SYSTEM',
    DEALER_NAME STRING COMMENT 'DEALER NAME',
    DEALER_TEL STRING COMMENT 'DEALER TELEPHONE NUMBER',
    DEALER_CITY STRING COMMENT 'DEALER CITY',
    DEALER_STATE STRING COMMENT 'DEALER STATE CODE',
    DEALER_ZIP STRING COMMENT 'DEALER ZIPCODE',
    PROD_TYPE STRING COMMENT 'PRODUCT TYPE CODE: V = VEHICLE, T = TIRES, E = EQUIPMENT, C = CHILD RESTRAINT',
    REPAIRED_YN STRING COMMENT 'WAS DEFECTIVE TIRE REPAIRED "Y" OR "N"',
    MEDICAL_ATTN STRING COMMENT 'WAS MEDICAL ATTENTION REQUIRED "Y" OR "N"',
    VEHICLES_TOWED_YN STRING COMMENT 'WAS VEHICLE TOWED "Y" OR "N"'
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hivevar:datalake_path}${hivevar:input_folder}/cmpl'
tblproperties ("skip.header.line.count"="0");

-- Contains raw vehicle recall data sourced from: 
-- https://static.nhtsa.gov/odi/ffdd/rcl/FLAT_RCL.zip
CREATE EXTERNAL TABLE IF NOT EXISTS ${hivevar:demo_db}.flat_rcl (
    RECORD_ID INT COMMENT 'RUNNING SEQUENCE NUMBER, WHICH UNIQUELY IDENTIFIES THE RECORD.',
    CAMPNO STRING COMMENT 'NHTSA CAMPAIGN NUMBER',
    MAKETXT STRING COMMENT 'VEHICLE/EQUIPMENT MAKE',
    MODELTXT STRING COMMENT 'VEHICLE/EQUIPMENT MODEL',
    YEARTXT STRING COMMENT 'MODEL YEAR, 9999 IF UNKNOWN or N/A',
    MFGCAMPNO STRING COMMENT 'MFR CAMPAIGN NUMBER',
    COMPNAME STRING COMMENT 'COMPONENT DESCRIPTION',
    MFGNAME STRING COMMENT 'MANUFACTURER THAT FILED DEFECT/NONCOMPLIANCE REPORT',
    BGMAN STRING COMMENT 'BEGIN DATE OF MANUFACTURING',
    ENDMAN STRING COMMENT 'END DATE OF MANUFACTURING',
    RCLTYPECD STRING COMMENT 'VEHICLE, EQUIPMENT OR TIRE REPORT',
    POTAFF INT COMMENT 'POTENTIAL NUMBER OF UNITS AFFECTED ',
    ODATE STRING COMMENT 'DATE OWNER NOTIFIED BY MFR',
    INFLUENCED_BY STRING COMMENT 'RECALL INITIATOR (MFR/OVSC/ODI)',
    MFGTXT STRING COMMENT 'MANUFACTURERS OF RECALLED VEHICLES/PRODUCTS',
    RCDATE STRING COMMENT 'REPORT RECEIVED DATE',
    DATEA STRING COMMENT 'RECORD CREATION DATE',
    RPNO STRING COMMENT 'REGULATION PART NUMBER',
    FMVSS STRING COMMENT 'FEDERAL MOTOR VEHICLE SAFETY STANDARD NUMBER',
    DESC_DEFECT STRING COMMENT 'DEFECT SUMMARY',
    CONEQUENCE_DEFECT STRING COMMENT 'CONSEQUENCE SUMMARY',
    CORRECTIVE_ACTION STRING COMMENT 'CORRECTIVE SUMMARY',
    NOTES STRING COMMENT 'RECALL NOTES',
    RCL_CMPT_ID STRING COMMENT 'NUMBER THAT UNIQUELY IDENTIFIES A RECALLED COMPONENT.',
    MFR_COMP_NAME STRING COMMENT 'MANUFACTURER-SUPPLIED COMPONENT NAME',
    MFR_COMP_DESC STRING COMMENT 'MANUFACTURER-SUPPLIED COMPONENT DESCRIPTION',
    MFR_COMP_PTNO STRING COMMENT 'MANUFACTURER-SUPPLIED COMPONENT PART NUMBER'
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hivevar:datalake_path}${hivevar:input_folder}/rcl'
tblproperties ("skip.header.line.count"="0");

-- Contains raw customer investigation data sourced from: 
-- https://static.nhtsa.gov/odi/ffdd/inv/FLAT_INV.zip
CREATE EXTERNAL TABLE IF NOT EXISTS ${hivevar:demo_db}.flat_inv (
    NHTSA_ACTION_NUMBER STRING COMMENT 'NHTSA Identification Number',
    MAKE STRING COMMENT 'Vehicle/Equipment Make',
    MODEL STRING COMMENT 'Vehicle/Equipment Model',
    YEAR STRING COMMENT 'Model Year, 9999 if Unknown or N/A',
    COMPNAME STRING COMMENT 'Component Description',
    MFR_NAME STRING COMMENT 'Manufacturer Name',
    ODATE STRING COMMENT 'Date Opened (YYYYMMDD)',
    CDATE STRING COMMENT 'Date Closed (YYYYMMDD)',
    CAMPNO STRING COMMENT 'Recall Campaign Number, if applicable',
    SUBJECT STRING COMMENT 'Summary Description',
    SUMMARY STRING COMMENT 'Summary Detail'
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
LOCATION '${hivevar:datalake_path}${hivevar:input_folder}/inv'
tblproperties ("skip.header.line.count"="0");